mysql:
  auth:
    rootPassword: rootpass123
    username: demo
    password: demopass123
    database: demo_db

  primary:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 8Gi

  metrics:
    enabled: true

# 👇 Required by service.yaml and other templates
service:
  type: ClusterIP     # Added this to fix nil pointer errors for .Values.service.type
  port: 3306

# 👇 Required by serviceaccount.yaml template
serviceAccount:
  create: true

ingress:
  enabled: false
  annotations: {}
  className: ""
  tls: []
  hosts: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent
