{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgresql-wrapper.serviceAccountName" . }}
  labels:
    {{- include "postgresql-wrapper.labels" . | nindent 4 }}
{{- end }}
