apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-wrapper.fullname" . }}
  labels:
    {{- include "postgresql-wrapper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.primary.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.postgresql.primary.service.port | default 5432 }}
      targetPort: {{ .Values.postgresql.primary.service.port | default 5432 }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "postgresql-wrapper.selectorLabels" . | nindent 4 }}
